name: Simple Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect and run on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 3.110.xxx.xxx   # 👈 REPLACE with your actual EC2 Public IP
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Connected to EC2"

            # Create file
            echo 'print("Hello from EC2 🚀")' > app.py

            # Run app in background
            nohup python3 app.py > output.log 2>&1 &
